StripeFundamentals.Web/Controllers/BookController.cs
using StripeFundamentals.Models.Book;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Stripe;
using StripeFundamentals.Web.Services;


namespace StripeFundamentals.Controllers
{
    public class BookController : Controller
    {
        // embedded form
        public ActionResult Index()
        {
            string stripePublishableKey = ConfigurationManager.AppSettings["stripePublishableKey"];
            var model = new IndexViewModel() { StripePublishableKey = stripePublishableKey };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken()]
        public ActionResult Charge(ChargeViewModel chargeViewModel)
        {
            Debug.WriteLine(chargeViewModel.StripeEmail);
            Debug.WriteLine(chargeViewModel.StripeToken);
            return RedirectToAction("Confirmation");
        }

        public ActionResult Custom()
        {
            string stripePublishableKey = ConfigurationManager.AppSettings["stripePublishableKey"];
            var model = new CustomViewModel() { StripePublishableKey = stripePublishableKey, PaymentFormHidden = true };
            return View(model);
        }


        [HttpPost]
        [ValidateAntiForgeryToken()]
        public ActionResult Custom(CustomViewModel customViewModel)
        {
            customViewModel.PaymentFormHidden = false;
            var chargeOptions = new StripeChargeCreateOptions()
            {
                //required
                Amount = 3900,
                Currency = "usd",
                Source = new StripeSourceOptions() { TokenId = customViewModel.StripeToken },
                //optional
                Description = string.Format("JavaScript Framework Guide Ebook for {0}", customViewModel.StripeEmail),
                ReceiptEmail = customViewModel.StripeEmail
            };


            var chargeService = new StripeChargeService();

            try
            {
                StripeCharge stripeCharge = chargeService.Create(chargeOptions);
                
                //Validate charge
                chargeService.Capture(stripeCharge.Id);

                if (stripeCharge.Status == "succeeded")
                {
                    //creating the customer and add it to stripe
                    var newCustomer = new StripeCustomerService().Create(
                        new StripeCustomerCreateOptions
                        {
                            Email = customViewModel.StripeEmail
                        }
                        );
                    // CREATE NEW INVOICE
                    // var invoiceService = new StripeInvoiceService();
                    // StripeInvoice response = invoiceService.Create(newCustomer.Id); // optional StripeInvoiceCreateOptions
                    //var response = invoiceService.Upcoming(newCustomer.Id);
                    // stripeCharge.InvoiceId = response.Id;


                    //SEND THE CONFIRMATION
                    var emailService = new EmailService();
                    emailService.SendPaymentReceivedFromChargeEmail(stripeCharge);

                }
            }
            catch (StripeException stripeException)
            {
                Debug.WriteLine(stripeException.Message);
                ModelState.AddModelError(string.Empty, stripeException.Message);
                return View(customViewModel);
            }

            return RedirectToAction("Confirmation");

        }



        public ActionResult Confirmation()
        {
            return View();
        }


    }
}

StripeFundamentals.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StripeFundamentals.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

StripeFundamentals.Web/Controllers/SubscriptionController.cs
using StripeFundamentals.Models.Subscription;
using StripeFundamentals.Web.Services;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StripeFundamentals.Web.Controllers;
using Stripe;


namespace StripeFundamentals.Controllers
{
    public class SubscriptionController : Controller
    {
        private IPlanService planService;

        private ISubscriptionService subscriptionService;
        public ISubscriptionService SubscriptionService
        {
            get
            {
                return subscriptionService ?? new SubscriptionService();
            }
            private set
            {
                subscriptionService = value;
            }
        }

        public SubscriptionController(IPlanService planService, ISubscriptionService subscriptionService)
        {
            this.planService = planService;
            this.subscriptionService = subscriptionService;
        }


        public SubscriptionController()
        {

        }

        public IPlanService PlanService
        {
            get
            {
                return planService ?? new PlanService();
            }
            private set
            {
                planService = value;
            }
        }


        // GET: Subscription
        public ActionResult Index()
        {
            var viewModel = new IndexViewModel() { Plans = PlanService.List() };
            return View(viewModel);
        }

        public ActionResult Billing(int planId)
        {
            string stripePublishableKey = ConfigurationManager.AppSettings["stripePublishableKey"];
            var viewModel = new BillingViewModel() { Plan = PlanService.Find(planId), StripePublishableKey = stripePublishableKey };
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Billing(BillingViewModel billingViewModel)
        {
            billingViewModel.Plan = PlanService.Find(billingViewModel.Plan.Id);
            try
            {
                SubscriptionService.Create(User.Identity.Name, billingViewModel.Plan, billingViewModel.StripeToken);


                //if (stripeCharge.Status == "succeeded")
                //{
                //    //creating the customer and add it to stripe
                //    var newCustomer = new StripeCustomerService().Create(
                //        new StripeCustomerCreateOptions
                //        {
                //            Email = customViewModel.StripeEmail
                //        }
                //        );
                //}
            }
            catch (StripeException stripeException)
            {
                ModelState.AddModelError(string.Empty, stripeException.Message);
                return View(billingViewModel);
            }
            return RedirectToAction("Index", "Dashboard");
        }
       


        
    }
}

StripeFundamentals.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

StripeFundamentals.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

StripeFundamentals.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Stripe</h1>
    <p class="lead">Easy payments for developers.</p>
    <p><a href="http://stripe.com/docs" target="_blank" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>One-time Payment</h2>
        <p>
            This demo shows how to accept a one-time payment for a book with an embedded form.
        </p>
        <p>@Html.ActionLink("Details", "Index", "Book", routeValues: null, htmlAttributes: new { @class = "btn btn-default" })</p>
    </div>
    <div class="col-md-4">
        <h2>One-time Payment Custom</h2>
        <p>
            This demo shows how to accept a one-time payment for a book with a custom form.
        </p>
        <p>@Html.ActionLink("Details", "Custom", "Book", routeValues: null, htmlAttributes: new { @class = "btn btn-default" })</p>
    </div>
    <div class="col-md-4">
        <h2>Subscription Payments</h2>
        <p>This demo shows you how to accept recurring payments for a subscription software service.</p>
        <p>@Html.ActionLink("Details", "Index", "Subscription", routeValues: null, htmlAttributes: new { @class = "btn btn-default" })</p>
    </div>
</div>